on:
  push:
    branches:
      - main
jobs:
  change-deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: "Check-out"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Run git log to file"
        # You may pin to the exact commit or the version.
        run: git log main --stat --pretty=format:"%ai - %s" > "/home/runner/work/constantinopal/constantinopal/public/CHANGELOG.md"
        # You may pin to the exact commit or the version.
        # uses: bcomnes/deploy-to-neocities@e3fac0f3dea69f575e7e30e39afb18d4dad01a09
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v2.0.2
        with:
          # Neocities API token for site to deploy to
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          # Local folder to deploy to neocities
          dist_dir: public
          # Delete orphaned files on neocities that don't exist in distDir
          cleanup: true
          # A glob string that prevents matched files from ever being deleted.
          #protected_files: # optional